backend:
  name: github
  repo: hu-wentao/hu-wentao.github.io
  branch: main
  app_id: 3037472
  base_url: https://api.sveltia.org # 强制使用 Sveltia 的验证网关
  auth_endpoint: auth

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "正文", name: "body", widget: "markdown" }
